"""X96S wifi driver table: the runtime load set for the dispatcher.

One row per supported board revision: (SDIO/USB VID, PID, image path
inside vendor_dlkm, payload file next to the launch dir). Every payload
is built with internal module name `dhd` (see README §8: the Broadcom HAL
hardcodes /sys/module/dhd/...) under its own file name — only the
dispatcher-selected one is ever loaded, so the shared internal name
never collides.

To add a revision: build its driver with the same pipeline (modname dhd
+ power/reinit quirks as needed + -ENODEV on foreign hardware, never
stripped), drop the payload next to fix_x96s.py, append one row.
vendor_dlkm has room for ~1 more uncompressed driver (912 free blocks
left after 8723bs; measured, not estimated — see wifi_multiload.md §6).
"""

import os

from . import PROJECT_ROOT
from .errors import FixError

# (vid, pid, image path, payload file).
WIFI_DRIVERS: tuple[tuple[int, int, str, str], ...] = (
    (0x024c, 0xb723, "lib/modules/x96s_8723bs.ko",
     "x96s_8723bs-4.9.337.ko"),
)

DISPATCHER_IMAGE_PATH = "bin/x96s_wifi"
DISPATCHER_PAYLOAD = "x96s_wifi"
MAP_IMAGE_PATH = "etc/wifi/x96s_wifi.map"

_WIFI_CACHE: dict[str, bytes] = {}


def load_payload(filename: str, desc: str) -> bytes:
    """Read a build payload, searched next to CWD, then the repo root."""
    if filename in _WIFI_CACHE:
        return _WIFI_CACHE[filename]
    tried: list[str] = []
    search_dirs = [os.getcwd(), PROJECT_ROOT]
    for base in search_dirs:
        path = os.path.join(base, filename)
        tried.append(path)
        if os.path.isfile(path):
            with open(path, "rb") as handle:
                data = handle.read()
            if not data.startswith(b"\x7fELF"):
                raise FixError("%s payload is not ELF: %s" % (desc, path))
            _WIFI_CACHE[filename] = data
            return data
    raise FixError("%s payload not found (tried: %s); build it (see "
                   "README.md) and place it at %s"
                   % (desc, ", ".join(tried), filename))


def build_map() -> bytes:
    """Generate the dispatcher map file from WIFI_DRIVERS."""
    lines = ["# x96s_wifi map: VID PID /vendor_dlkm/...ko (hex, first wins)",
             "# generated by fix_x96s.py, do not hand-edit in the image"]
    for vid, pid, img_path, _payload in WIFI_DRIVERS:
        lines.append("%04x %04x /vendor_dlkm/%s" % (vid, pid, img_path))
    return ("\n".join(lines) + "\n").encode("ascii")


def selinux_xattr(context: str) -> tuple[str, bytes]:
    """(name, value) pair for a create-op (values are NUL-terminated)."""
    return ("security.selinux", (context + "\x00").encode("ascii"))
